// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hangsheng.kaoqin.domain;

import com.hangsheng.kaoqin.domain.AttendanceStatBean;
import io.springlets.format.EntityFormat;

privileged aspect AttendanceStatBean_Roo_DTO {
    
    declare @type: AttendanceStatBean: @EntityFormat;
    
}
