// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hangsheng.kaoqin.web;

import com.hangsheng.kaoqin.web.AttendancesSearchThymeleafController;
import com.hangsheng.kaoqin.web.AttendancesSearchThymeleafLinkFactory;
import io.springlets.web.mvc.util.MethodLinkFactory;
import org.springframework.stereotype.Component;

privileged aspect AttendancesSearchThymeleafLinkFactory_Roo_LinkFactory {
    
    declare parents: AttendancesSearchThymeleafLinkFactory implements MethodLinkFactory<AttendancesSearchThymeleafController>;
    
    declare @type: AttendancesSearchThymeleafLinkFactory: @Component;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String AttendancesSearchThymeleafLinkFactory.STATSIGNINAFTERANDSIGNOUTBEFOREFORM = "statSignInAfterAndSignOutBeforeForm";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String AttendancesSearchThymeleafLinkFactory.STATSIGNINAFTERANDSIGNOUTBEFORE = "statSignInAfterAndSignOutBefore";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String AttendancesSearchThymeleafLinkFactory.BYSIGNINAFTERANDSIGNOUTBEFOREDT = "bySignInAfterAndSignOutBeforeDt";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String AttendancesSearchThymeleafLinkFactory.BYSIGNINAFTERANDSIGNOUTBEFOREFORM = "bySignInAfterAndSignOutBeforeForm";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String AttendancesSearchThymeleafLinkFactory.BYSIGNINAFTERANDSIGNOUTBEFORE = "bySignInAfterAndSignOutBefore";
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Class
     */
    public Class<AttendancesSearchThymeleafController> AttendancesSearchThymeleafLinkFactory.getControllerClass() {
        return AttendancesSearchThymeleafController.class;
    }
    
}
